export { default as HeroSection } from './HeroSection'
export { default as ViralProductsSection } from './ViralProductsSection'
export { default as PsychologySection } from './PsychologySection'
export { default as UrgencySection } from './UrgencySection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as InstagramSection } from './InstagramSection'